# Generated by Django 6.0.6 on 2026-06-22 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='borrowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Читатель'),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
    ]
